config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/club', to: 'static_pages#club'

  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: {message: "Rentrez une adresse email valide de moins de 255 caractères."}, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX, message: "Format d'email invalide" },
                    uniqueness: { case_sensitive: false, message: "L'email est déjà pris" }

  validates :first_name, presence: {message: "Rentrez votre prénom"}
  validates :last_name, presence: {message: "Rentrez votre nom"}

  has_secure_password validations: false
  validates :password, presence: true,
                       confirmation: {message: "Les mots de passe ne correspondent pas"},
                       length: { in: 6..40, message: "Rentrez un mot de passe entre 6 et 40 caractères" }
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end                    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # create a new session
    # first get the user
    user = User.find_by(email: params[:session][:email].downcase)
    # if user isn't nil and if the password is correct
    if user && user.authenticate(params[:session][:password])
      # log_in (go to sessions_helper)
      log_in(user)
      redirect_to "/club", flash: {success: 'Connecté !'}
    else
      redirect_to "/login", flash: { danger: 'Mauvaise combinaison email/mot de passe. Essayez de nouveau'}
    end
  end

  def destroy
    log_out
    redirect_to root_url, flash: { success: "Déconnecté !" }
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def club
    @users = User.all
    if logged_in?
      # then stay on secret_page
    else
      # else redictiion to the login page with a beautiful flash
      redirect_to "/login", flash: { flash: "hey login-toi pour y accéder" }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      # Handle a successful save.
      redirect_to("/users/" + @user.id.to_s)
      flash[:success] = "Profil utilisateur créé"
      log_in(@user)
    else
      flash[:danger] = "bug"
      render 'new'
    end
  end

  def edit
    @user = current_user
    # if no user logged
    if @user == nil
      redirect_to login_path
      # go to edit page
    elsif @user.id == params[:id].to_i
      # else case are wrong users
    else
      redirect_to login_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>THPTestingRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Accueil", root_path, id: "logo" %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
        <% if logged_in? %>
            <li><%= link_to "Club", club_path, class:"nav-link" %></li>
            <li><%= link_to "Profile", current_user, class:"nav-link" %></li>
            <li><%= link_to "Log out", logout_path, method: :delete, class:"nav-link" %></li>
        <% else %>
          <li><%= link_to "Log in", login_path, class:"nav-link" %></li>
          <li><%= link_to "Sign up", new_user_path, class:"nav-link"%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
    <%= yield %>
  </body>
</html>

app/views/shared/_error.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Le formulaire contient <%= pluralize(@user.errors.count, "erreur") %>.
    </div>
    <ul>
    <% @user.errors.values.each do |msg| %>
      <li><%= msg.first %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/club.html.erb
<html>
<h1>Le club</h1>

<p>Voici tous les membres du club :</p>
<br>
<% @users.each do |user|%>
  <li>
   <%= user.first_name + " " + user.last_name%>
   <%= link_to("Profile", "/users/#{user.id.to_s}") %>
  </li>
<% end %>
</html>

app/views/static_pages/home.html.erb
<html>
<h1>Le site du club</h1>

<% if logged_in? %>
  <p> Hey, accède au club <a href="/club">ici</a></p>
  
<% else %>

  <p>Yo, si tu veux faire partie du club et savoir qui d'autre en fait partie il faut <a href="/users/new">t'inscrire</a></p>
  <br>
  <p>Déjà inscrit ? <a href="/login">Connecte-toi</a></p>

  <% end %>
</html>

app/views/users/new.html.erb
<h1>S'inscrire</h1>
<br>
<%= form_for(@user) do |f| %>
  <%= render "shared/error" %>
  <%= f.label :prénom %>
  <br>
  <%= f.text_field :first_name, placeholder: "Jean" , class: 'form-control'%>
  <br>
  <%= f.label :nom %>
  <br>
  <%= f.text_field :last_name, placeholder: "Dupont" , class: 'form-control'%>
  <br>
  <%= f.label :email %>
  <br>
  <%= f.email_field :email, placeholder: "exemple@exemple.com" , class: 'form-control'%>
  <small>Max 255 caractères</small>
  <br>
  <%= f.label :password %>
  <br>
  <%= f.password_field :password, placeholder: "Mot de passe" , class: 'form-control'%>
  <small>Entre 6 et 40 caractères</small>
  <br>
  <%= f.label :password_confirmation, "Confirmation" %>
  <br>
  <%= f.password_field :password_confirmation, placeholder: "Confirmer mot de passe" , class: 'form-control'%>
  <small>Les mots de passe doivent correspondre</small>
  <br>
  <br>
  <%= f.submit "Créer mon compte", class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<p>Prénom  : <%= @user.first_name %></p>
<br>
<br>
<p>Nom : <%= @user.last_name %></p>
<br>
<br>
<p>Email : <%= @user.email %></p>
<br>
<%= link_to "Editer mon compte", edit_user_path, class: "btn btn-primary" %>
<br>
<br>
<%= link_to "Supprimer mon compte", @user, class: "btn btn-primary", method: :delete %>